steps:
# Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
# Build
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  env:
    - 'GENERATE_SOURCEMAP=false'
#Docker build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/home-$BRANCH_NAME:1.0.$BUILD_ID', '.']
  timeout: 180s
# Push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/home-$BRANCH_NAME:1.0.$BUILD_ID']
# Set
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - -l
  - app=home,branch=$BRANCH_NAME
  - home=gcr.io/$PROJECT_ID/home-$BRANCH_NAME:1.0.$BUILD_ID
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=livox'